name: proxy_demo
description: a proxy client application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.2+3

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  fluro: ^2.0.3
  shared_preferences: ^2.1.2
  webview_flutter: ^3.0.4
  flutter_login: ^3.2.0
  flutter_easyrefresh: ^2.1.8
  intl: ^0.18.0
  path_provider: ^2.0.10
  crisp: ^0.3.1
  modal_bottom_sheet: ^3.0.0-pre
  meta: ^1.7.0
  stylish_bottom_bar: ^1.0.1
  flutter_chat_ui: ^1.6.8
  get: ^4.6.5
  card_swiper: ^2.0.4
  awesome_dialog: ^3.1.0
  flutter_widget_from_html_core: ^0.10.1
  tab_indicator_styler: ^2.0.0
  pull_to_refresh_flutter3: ^2.0.1
  shirne_dialog: ^4.5.0
  flutter_native_splash: ^2.3.0
  uuid: ^3.0.7
  flutter_chat_bubble: ^2.0.2
  bubble: ^1.2.1
  fluttertoast: ^8.0.9
  flutter_icmp_ping: ^3.1.0
  provider: ^6.0.3
  flutter_screenutil: ^5.5.3+2

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/flags/
    - assets/images/
    - assets/